<a href="https://colab.research.google.com/github/cyeef/Data-Science-Portfolio-C21-/blob/main/Exercises/5a-Numpy.Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Playing with NumPY

## Setup: Import numpy

In [1]:
import numpy as np

## Problem 1: random integers



### Part 1


Create a 1 dimensional array with 10 random integers

In [2]:
x = np.array([26, 12, 69, 54, 3, 78, 9, 87, 45, 42])
print(x)

[26 12 69 54  3 78  9 87 45 42]


### Part 2


Create a second 1 dimensional array with 10 random integers.  Concatenate it with your first array to create a 2 dimensional array with shape (2,10).

**Note:**  You may have to get creative to make this work.  

In [7]:
# y = np.array([1, 40, 26, 23, 16, 99, 39, 90, 7, 0])  # added values and made one array
y = np.array([1, 40, 26, 23, 16, 99, 39, 90, 7, 0])
z = np.vstack([x, y])
print(z)
z.shape


[[26 12 69 54  3 78  9 87 45 42]
 [ 1 40 26 23 16 99 39 90  7  0]]


(2, 10)

### Part 3


Use indexing to access the first two columns in the array you created in #2.

In [8]:
ind = z[:, 0:2]
print(ind)

[[26 12]
 [ 1 40]]


## Problem 2: 2D array



Convert the array below into a 2 dimensional array


```python
arr = np.arange(70)
```

In [11]:
#arr = np.arange(70)
#arr2 = np.vstack([arr])
#print(arr)
#print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]]


In [13]:
arr = np.arange(70)

arr2 =arr.reshape(7, 10)
print(arr2)
arr2.shape

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


(7, 10)

## Problem 3: multiply


Multiply all numbers in the array below by a number of your choice.

```python
arr = np.arange(30)
```

In [ ]:
#arr = np.arange(30)     LOOP 30 TIMES - WRONG ANSWER
#arr1 = []
#x = [arr * 5 for x in arr]
#x.append(arr)
#print(x)

In [20]:
# For Numpy
arr = np.arange(30)
arr1 = arr * 5
print(arr)
print(arr1)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145]
(30,)


## Problem 4: stats


Find the min, max, mean, sample standard deviation, and population standard deviation for the array below.

```python
arr = np.random.normal(5,10,10000)
```


In [29]:
arr = np.random.normal(5,10,10000)
arr = np.random.normal(5, 10, 10000)

print('='*40)
print(f"{'Min':<25} {arr.min():.4f}")
print(f"{'Max':<25} {arr.max():.4f}")
print(f"{'Mean':<25} {arr.mean():.4f}")
print(f"{'Sample Std (ddof=1)':<25} {arr.std(ddof=1):.4f}")
print(f"{'Population Std (ddof=0)':<25} {arr.std():.4f}")
print('='*40)

Min                       -33.8186
Max                       39.1504
Mean                      4.9799
Sample Std (ddof=1)       9.9711
Population Std (ddof=0)   9.9706


## Problem 5: filtering


### Part 1


Create a 4X6 array with random integers between 0 and 10.  


In [33]:
arr = np.random.randint(0, 11, size = (4, 6))
print(arr)
print(arr.shape)

[[4 3 2 2 4 2]
 [8 6 2 1 4 2]
 [2 7 3 9 9 8]
 [1 6 9 7 8 8]]
(4, 6)


### Part 2


Create a boolean array with `True` entries where the entries in your array are greater than 6


In [38]:
arr = np.arange(30)
arr1 = arr > 6
print(arr[arr1])

print(arr.shape)

[ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
(30,)


### Part 3


Use your boolean array as a filter to pull out the entries greater than 6

In [39]:
print(arr[arr > 6])

[ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


Numpy has many functions and methods.  Explore them to see what they do.

- [numpy at w3school]( https://www.w3schools.com/python/numpy/default.asp )
- [numpy at numpy.org]( https://numpy.org/doc/2.2/user/quickstart.html )
- [blog at medium.com]( https://medium.com/@brusooo27/40-most-used-numpy-methods-c2e3ed2018d4 )